Задача №1

In [ ]:
import numpy as np
A = np.array([[1, 2, 1],
             [-2, 1, 1]])

B = np.array([[3, 1],
             [-1, 0],
             [2, 4]])

C = np.array([[-2, 2],
             [1, -1],
             [1, 2]])

print(A.T + 2*B)
print(B + 2*C)


[[7 0]
 [0 1]
 [5 9]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задача №2

In [ ]:
import numpy as np
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задача №3

In [ ]:
import numpy as np
A = np.arange(0.0, 1.5, 0.1).reshape((5,3))
B = np.arange(1, 7, 1).reshape((3,2))
print(A)
print(B)
print(np.dot(A,B))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Задача №4

In [ ]:
import numpy as np
A = np.arange(1, 36*2, 2, dtype=np.int32)
print(A)

for x in A:
  if x%3 == 0:
    print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
3
9
15
21
27
33
39
45
51
57
63
69
